export const SITE_NAME = "axonz.ai";
export const SITE_TAGLINE = "Voice Intelligence · Engineered";

export const PRICING = {
  IN: [
    {
      badge: "Starter",
      name: "Pilot",
      featured: false,
      price: "₹5.99",
      unit: "/min",
      volume: "Up to 3,000 mins/month",
      desc: "Perfect for testing your first voice bot use case with real traffic.",
      features: [
        "Up to 3,000 minutes/month",
        "3 Indian languages",
        "Basic dashboard & analytics",
        "CRM webhook integration",
        "Email support",
      ],
      cta: "Start Free Pilot",
      note: "≈ ₹17,970/mo for 3,000 mins",
    },
    {
      badge: "Most Popular",
      name: "Growth",
      featured: true,
      price: "₹5.49",
      unit: "/min",
      volume: "Up to 30,000 mins/month",
      desc: "For teams scaling voice automation across inbound and outbound.",
      features: [
        "Up to 30,000 minutes/month",
        "All 12+ Indian languages",
        "Advanced analytics & recordings",
        "Live agent handoff",
        "TRAI DND compliance",
        "Priority support",
      ],
      cta: "Get Started →",
      note: "≈ ₹1,64,700/mo for 30,000 mins",
    },
    {
      badge: "Enterprise",
      name: "Scale",
      featured: false,
      price: "₹4.99",
      unit: "/min",
      volume: "100,000+ mins/month",
      desc: "Large-volume deployments with compliance and custom model needs.",
      features: [
        "Unlimited minutes",
        "Custom language fine-tuning",
        "SLA guarantees + 24/7 support",
        "RBI / IRDAI compliance pack",
        "Custom integrations",
      ],
      cta: "Contact Sales",
      note: "Volume discounts available",
    },
  ],
  US: [
    {
      badge: "Starter",
      name: "Pilot",
      featured: false,
      price: "$0.10",
      unit: "/min",
      volume: "Up to 3,000 mins/month",
      desc: "Test your first AI voice agent with real US traffic.",
      features: [
        "Up to 3,000 minutes/month",
        "English + Spanish support",
        "Basic dashboard & analytics",
        "CRM webhook integration",
        "Email support",
      ],
      cta: "Start Free Pilot",
      note: "≈ $300/mo for 3,000 mins",
    },
    {
      badge: "Most Popular",
      name: "Growth",
      featured: true,
      price: "$0.09",
      unit: "/min",
      volume: "Up to 30,000 mins/month",
      desc: "Scale voice automation for US inbound and outbound operations.",
      features: [
        "Up to 30,000 minutes/month",
        "150+ languages globally",
        "Advanced analytics & recordings",
        "Live agent handoff",
        "TCPA compliance ready",
        "Priority support",
      ],
      cta: "Get Started →",
      note: "≈ $2,700/mo for 30,000 mins",
    },
    {
      badge: "Enterprise",
      name: "Scale",
      featured: false,
      price: "$0.08",
      unit: "/min",
      volume: "100,000+ mins/month",
      desc: "High-volume US deployments with dedicated infrastructure.",
      features: [
        "Unlimited minutes",
        "Custom voice fine-tuning",
        "SLA guarantees + 24/7 support",
        "HIPAA + SOC2 compliance pack",
        "Custom integrations",
      ],
      cta: "Contact Sales",
      note: "Volume discounts available",
    },
  ],
};
